#--- JPF project properties file for project jpf-nas
jpf-nas = ${config_path}

#--- other JPF projects we depend on
@using jpf-core

#--- project specific host VM classpath (used by Java to load classes)
jpf-nas.native_classpath =\
   ${jpf-nas}/build/libs/jpf-nas.jar;\
   ${jpf-nas}/lib/*.jar

#--- project specific JPF classpath (used by JPF to load system-under-test classes)
jpf-nas.classpath =\
   ${jpf-nas}/build/libs/jpf-nas-classes.jar;\
   ${jpf-nas}/build/classes/java/examples;\
   ${jpf-nas}/build/classes/java/main

#--- where are the classes for the JPF regression tests (used by host VM and JPF)
jpf-nas.test_classpath =\
   ${jpf-nas}/build/classes/java/test;\
   ${jpf-nas}/build/classes/java/main;\
   ${jpf-nas}/build/libs/jpf-nas-classes.jar

#--- project specific JPF sourcepath (used by JPF to locate sources)
jpf-nas.sourcepath =\
   ${jpf-nas}/src/examples;\
   ${jpf-nas}/src/tests;\
   ${jpf-nas}/src/main

#--- project specific peer packages
jpf-nas.peer_packages = nas.java.net

vm.scheduler_factory.class = gov.nasa.jpf.vm.DistributedSchedulerFactory
vm.class = nas.NasVM
vm.process_finalizers = true
vm.nas.initiating_target = -1
