jpf-nas = ${config_path}

@using jpf-core

jpf-nas.classpath = \
  ${jpf-nas}/build/classes/java/main:\
  ${jpf-nas}/build/classes/java/test:\
  ${jpf-nas}/build/classes/java/examples:\
  ${jpf-nas}/build/classes/modules:\
  ${jpf-nas}/build/libs/jpf-nas-classes.jar

jpf-nas.native_classpath = \
  ${jpf-nas}/build/libs/jpf-nas.jar:\
  ${jpf-nas}/lib/*.jar

jpf-nas.peer_packages = nas.java.net
vm.class = nas.NasVM
vm.scheduler_factory.class = gov.nasa.jpf.vm.DistributedSchedulerFactory
vm.process_finalizers = true
vm.nas.initiating_target = -1

target=nas.util.test.TestNasJPF
